# runtime image
FROM scratch
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/go-find-archived-gh-actions /go/bin/go-find-archived-gh-actions
# Run the binary.
ENTRYPOINT ["/go/bin/go-find-archived-gh-actions"]
